import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { InstallResult } from "./agent-installer";

// opencode has no JSON hook config file the way codex/claude-code/antigravity do. Its only native
// extension point for per-session capture is the plugin API, so smem installs a small plugin file
// (`smem.ts`) instead of writing a hooks.json. The plugin forwards agent events to the same
// `smem hook run --agent opencode` capture pipeline the other agents use.
const PLUGIN_FILE_NAME = "smem.ts";

// Ownership marker: uninstall only removes a plugin file that actually contains our capture
// invocation, mirroring isSmemHookCommand for the JSON-based agents.
const SMEM_MARKER = "smem hook run --agent opencode ";

export function opencodePluginPath(options: { cwd: string; global?: boolean; home?: string }): string {
  const base = options.global
    ? join(options.home ?? homedir(), ".config", "opencode")
    : join(resolve(options.cwd), ".opencode");
  return join(base, "plugin", PLUGIN_FILE_NAME);
}

export function installOpencodeHooks(options: {
  cwd: string;
  global?: boolean;
  home?: string;
  dryRun?: boolean;
}): InstallResult {
  const filePath = opencodePluginPath(options);
  const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : "";
  const generated = opencodePluginContent();

  let changed: boolean;
  let next = existing;

  if (existing.includes(SMEM_MARKER)) {
    changed = existing !== generated;
    next = generated;
  } else if (existing.trim()) {
    // A user-owned plugin already occupies this path; never clobber it.
    changed = false;
  } else {
    changed = true;
    next = generated;
  }

  if (changed && !(options.dryRun ?? false)) {
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, next, "utf8");
  }

  return {
    agent: "opencode",
    filePath,
    changed,
    kind: "hooks"
  };
}

export function uninstallOpencodeHooks(options: {
  cwd: string;
  global?: boolean;
  home?: string;
  dryRun?: boolean;
}): InstallResult {
  const filePath = opencodePluginPath(options);
  const existing = existsSync(filePath) ? readFileSync(filePath, "utf8") : "";

  if (!existing.includes(SMEM_MARKER)) {
    return {
      agent: "opencode",
      filePath,
      changed: false,
      kind: "hooks"
    };
  }

  if (!(options.dryRun ?? false)) {
    rmSync(filePath, { force: true });
  }

  return {
    agent: "opencode",
    filePath,
    changed: true,
    kind: "hooks"
  };
}

function opencodePluginContent(): string {
  return `// Generated by smem. Do not edit manually.
// smem hook run --agent opencode --event <event>  (ownership marker for smem uninstall)
// opencode hook capture: forwards agent events to smem via a native opencode plugin.
import { spawn } from "node:child_process";

const AGENT = "opencode";

let projectDir = "";
let sessionId = "";

function capture(event: any, payload: any) {
  try {
    const child = spawn("smem", ["hook", "run", "--agent", AGENT, "--event", event], {
      cwd: projectDir,
      stdio: ["pipe", "ignore", "ignore"]
    });
    child.on("error", () => {});
    child.stdin.write(JSON.stringify({ cwd: projectDir, sessionId: sessionId, ...payload }));
    child.stdin.end();
  } catch {
    // Capture must never break opencode.
  }
}

function partText(part: any) {
  return part && typeof part === "object" && typeof part.text === "string" ? part.text : "";
}

export default async (input: any) => {
  projectDir = input.directory || "";
  return {
    "chat.message": async (hookInput: any, output: any) => {
      sessionId = hookInput.sessionID || "";
      const prompt = (output.parts || []).map(partText).filter(Boolean).join("\\n");
      if (prompt) {
        capture("UserPromptSubmit", { prompt });
      }
    },
    "tool.execute.after": async (hookInput: any, output: any) => {
      sessionId = hookInput.sessionID || "";
      capture("PostToolUse", {
        callId: hookInput.callID,
        tool: hookInput.tool,
        args: hookInput.args,
        tool_response: output.output || ""
      });
    },
    dispose: async () => {
      capture("Stop", {});
    }
  };
};
`;
}
